### ISSUE TITLE
Find command with different parameters to search specifically for chosen details

### ISSUE THREAD

**Issue by karrui** [CS2103AUG2017-F11-B3/main#21]

**Comment by yewshengkai** [comment]
Completed with extra features.
Find with all prefixes (name, address, email, phone, homepage and tags)
e.g. find john, returns john, john boe
find p/91234567, returns any person with phone 91234567
find p/91234567 81234567, returns any person with phone 91234567 and 81234567

findany john, returns johnson, johnny, john, john boe
findany p/9123, returns any person with phone containing 9123 (return 91234567 and 81234567...)
findany p/123 888, returns any person with phone containing 123 and 888 (return 91234567, 81234567 and 9888555...)

etc.

**Comment by karrui** [comment]
Implemented in https://github.com/CS2103AUG2017-F11-B3/main/pull/35
