### ISSUE TITLE
Suggesting: Adding Profile Picture to contacts (two ** from User Stories)

### ISSUE THREAD

**Issue by yewshengkai** [CS2103AUG2017-F11-B3/main#31]
Hi all, apparently we are done with all the three * in our User stories and we can start working more on two * features.

As mentioned in my title, I highly recommend the profile picture hehe. x)

Anyone interested?

**Comment by karrui** [comment]
I can pick it up! @yewshengkai @basyiro

**Comment by yewshengkai** [comment]
Nice. Lol I keep recalingl what we discuss last time regarding this.. the command to add be like .. add i/"C:/Users/Document/Image/profile_2103_17_2017.png".

**Comment by karrui** [comment]
Ya CLI no choice suck thumb
