### ISSUE TITLE
Log in functionality or no?

### ISSUE THREAD

**Issue by karrui** [CS2103AUG2017-F11-B3/main#36]
Our use cases all seem to refer to the user being logged in, but we yet do not have a log in screen. Push to 2.0 or do within 1.5?

**Comment by yewshengkai** [comment]
If got enough time, can explore that option. I feel that the priority is low-medium and high workload. Consider, single client (easy, 1 account 1 password_encrpyted) or multi client (complicated, need create account, login details, password encrption(more or less using MD5 hashing). x.x.. Local login? Server base? Facebook linked? 

My conclusion is that... Too much workload but the gain little for this project. Correct me if im wrong. x)

**Comment by karrui** [comment]
I agree lol, that’s why I trying to see other opinions. Will scrap all mentions of log-in from use cases then

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by karrui** [comment]
Issue resolved by https://github.com/CS2103AUG2017-F11-B3/main/pull/49
