### ISSUE TITLE
Change background of `clear` to be color appropriate instead of blinding white

### ISSUE THREAD

**Issue by karrui** [CS2103AUG2017-F11-B3/main#39]
Implementation is discussed in https://github.com/nus-cs2103-AY1718S1/forum/issues/86

**Comment by yewshengkai** [comment]
Noted. We got this issue? :o: 
Current theme is using facebook colors. Will implement back "DarkTheme" and "iungo basic" when theme selector is ready.

**Comment by karrui** [comment]
Yup, to note for when dark theme is back

Regards, Karrui
________________________________

**Comment by yewshengkai** [comment]
Implemented on theme selector.
