### ISSUE TITLE
Suggestion: add multiple remarks

### ISSUE THREAD

**Issue by shuang-yang** [CS2103AUG2017-F11-B3/main#72]
Currently, when adding remarks for a specific person (using the `remark` command), the user will need to provide the full text body of the remark every time. 

However, in real cases, a user might want to:
1. Add on to an existing remark
2. Provide a new remark not related to the existing one

It would be great if the app supports this feature.

**Comment by yewshengkai** [comment]
Hi @shuang-yang, thank you for the suggestion. x)
