### ISSUE TITLE
Same tag with different colors in two display panels

### ISSUE THREAD

**Issue by OscarWang114** [CS2103AUG2017-F11-B3/main#74]
<img width="582" alt="screen shot 2017-11-03 at 15 19 05" src="https://user-images.githubusercontent.com/30998659/32363472-93da5820-c03d-11e7-8244-e843ca9017be.png">
On the left, the color of the familiy tag in David Li is blue, while on the right it's red

**Comment by yewshengkai** [comment]
Oh interesting. thanks.x)

**Comment by karrui** [comment]
Thanks for the bug report, this has since been fixed as of https://github.com/CS2103AUG2017-F11-B3/main/pull/79, closing issue.
